brew/installed: Rewrite in Zsh, with the help of jq
Also install jq as a preliminary dependency in brew/init.

diff --git a/brew/installed b/brew/installed
--- a/brew/installed
+++ b/brew/installed
@@ -1,95 +1,65 @@
-#!/usr/bin/python
+#!/usr/bin/env zsh
 
-import argparse
-import json
-import os
-import re
-import subprocess
+# Return values: See brew_formula_installed_exact (except 0 means installed and
+# 1 is not applicable).
+brew_formula_installed () {
+    local formula prefix
+    formula=$1
+    prefix=$(brew --prefix $formula 2>/dev/null) || return 3
+    [[ ! -d $prefix ]] && return 2 || return 0
+}
 
-def brew_formula_installed(formula):
-    """Check if a formula is installed.
+# Return values:
+# 0: installed with the specified options;
+# 1: installed but with different options;
+# 2: not installed;
+# 3: error (e.g. unrecognized formula name).
+brew_formula_installed_exact () {
+    local -a opts
+    local formula prefix receipt
+    opts=(${=${@}}) # perform word splitting on all arguments
+    formula=$opts[1]
+    shift 1 opts
 
-    Parameters
-    ----------
-    formula : str
-        Formula name (possibly with a tap prefix).
+    prefix=$(brew --prefix $formula 2>/dev/null) || return 3
+    [[ -d $prefix ]] || return 2
+    receipt=$prefix/INSTALL_RECEIPT.json
+    [[ -f $receipt ]] || return 3 # keg exists but no receipt found
+    actual_opts=( $(jq -r '.used_options[]' <$receipt 2>/dev/null) )
 
-    Returns:
-    {0, 2, 3}
-        0 if formula is installed; 2 if formula is not installed; 3 if
-        an unknown error occured.
+    # compare opts to actual_opts (sort first)
+    opts=(${(o)opts})
+    actual_opts=(${(o)actual_opts})
+    [[ "$opts" == "$actual_opts" ]]
+}
 
-    """
-    try:
-        formula_keg = subprocess.check_output(["/usr/local/bin/brew", "--prefix", formula],
-                                              stderr=subprocess.PIPE).strip()
-    except subprocess.CalledProcessError:
-        return 3
+[[ $1 == (|-h|--help) ]] && {
+    cat >&2 <<EOF
+Usage:  installed formula
+        installed --exact optstring
 
-    return 0 if os.path.exists(formula_keg) else 2
+If --exact is specified, check if the formula is installed with the exact
+options as specified in the optstring (order is ignored). optstring looks like
+"mpv --with-bundle --with-vapoursynth" and may be broken into multiple
+arguments.
 
-def brew_formula_installed_exact(optstring):
-    """Check if a formula is installed with the expected options.
+Return values:
+    0   installed with the specified options (or installed if no --exact)
+    1   installed but with different options (N/A if no --exact)
+    2   not installed
+    3   error (e.g. unrecognized formula name)
 
-    Parameters
-    ----------
-    optstring : str
-        A string that usually follows ``brew install``, with the formula
-        name (possibly with a tap prefix) followed by installation
-        options.
+EOF
+    exit 3
+}
 
-    Returns
-    -------
-    {0, 1, 2, 3}
-        0 if formula is installed with the expected options; 1 if
-        formula is installed but with different options; 2 if formula is
-        not installed; 3 if an unknown error occured.
-
-    """
-    tokens = re.split(r"\s+", optstring)
-    formula_name = tokens[0]
-    formula_expected_options = set(tokens[1:])
-
-    try:
-        formula_keg = subprocess.check_output(["/usr/local/bin/brew", "--prefix", formula_name],
-                                              stderr=subprocess.PIPE).strip()
-    except subprocess.CalledProcessError:
-        return 3
-
-    if not os.path.exists(formula_keg):
-        return 2
-
-    formula_receipt = os.path.join(formula_keg, "INSTALL_RECEIPT.json")
-    if not os.path.exists(formula_receipt):
-        return 3
-
-    try:
-        with open(formula_receipt) as fp:
-            formula_metadata = json.load(fp)
-            formula_installed_options = set(formula_metadata["used_options"])
-    except Exception:
-        return 3
-
-    return 0 if formula_expected_options == formula_installed_options else 1
-
-def main():
-    """CLI interface.
-
-    Regular mode: Return status is one of 0, 2, and 3; meanings are
-    described in the docstring of brew_formula_installed.
-
-    Exact mode (--exact): Return status is one of 0, 1, 2, and 3; meanings are
-    described in the docstring of brew_formula_installed_exact.
-
-    """
-    parser = argparse.ArgumentParser()
-    parser.add_argument("--exact", action="store_true")
-    parser.add_argument("optstring")
-    args = parser.parse_args()
-    if args.exact:
-        exit(brew_formula_installed_exact(args.optstring))
-    else:
-        exit(brew_formula_installed(args.optstring))
-
-if __name__ == "__main__":
-    main()
+if [[ $1 == --exact ]]; then
+    shift
+    brew_formula_installed_exact $@
+else
+    (( $# > 1 )) || {
+        print 'Error: Wrong number of arguments.' >&2
+        exit 3
+    }
+    brew_formula_installed $1
+fi
