20150619 changeset

diff --git a/emacs/snippets/sh-mode/getopts b/emacs/snippets/sh-mode/getopts
--- a/emacs/snippets/sh-mode/getopts
+++ b/emacs/snippets/sh-mode/getopts
@@ -3,13 +3,13 @@
 # key: getopts
 # contributor: Zhiming Wang <zmwangx@gmail.com>
 # --
-while getopts ":h$2" opt; do
+while getopts "${2::h}" opt; do
     case $opt in
         h)
             cat <<EOF
-$1
+${1:
 
-Usage: `(file-name-nondirectory (buffer-file-name))` [options]
+}Usage: `(file-name-nondirectory (buffer-file-name))` [options]
 
 Options:
     -h  show this help and exit
@@ -20,7 +20,7 @@ EOF
         $0
         :) echo "\${RED}error: option -$OPTARG requires an argument\${RESET}" >&2; exit 1;;
         \\?) echo "\${RED}error: unrecognized option -$OPTARG\${RESET}" >&2; exit 1;;
-        *) echo "\${RED}error: getopts internal error: unrecgonized option name \$opt\${RESET}"; exit 1;;
+        *) echo "\${RED}error: getopts internal error: unrecgonized option name \$opt\${RESET}" >&2; exit 1;;
     esac
 done
 shift \$((OPTIND-1))
